repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort

- repo: https://github.com/psf/black
  rev: 24.1.0
  hooks:
  - id: black

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0
  hooks:
  - id: mypy
    additional_dependencies: ['types-dateparser', "pydantic"]

- repo: https://github.com/rhysd/actionlint
  rev: v1.6.27
  hooks:
    - id: actionlint
