name: "Semantic PR Title Check"

on:
    pull_request:
        types:
            - opened
            - edited
            - reopened
            - synchronize

jobs:
    validate-pr-title:
        name: PR Title has semantic versioning
        runs-on: ubuntu-latest
        steps:
            - uses: amannn/action-semantic-pull-request@v5
