name: pytests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Pytest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install requirements
      run: python3 -m pip install -r requirements.txt -r requirements-dev.txt
    - name: Run tests and collect coverage
      run: python3 -m pytest --cov --cov-report xml .
    - name: Upload coverage reports to Codecov with GitHub Action
      if: always()
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: PeterStolz/ContainerCrop
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.1
